# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2020.1\bin\cmake\win\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2020.1\bin\cmake\win\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\GIT\UnconstrainedEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\GIT\UnconstrainedEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install\local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	echo >nul && "C:\Program Files\JetBrains\CLion 2020.1\bin\cmake\win\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install\local

# Special rule for the target install/local
install\local\fast: preinstall\fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	echo >nul && "C:\Program Files\JetBrains\CLion 2020.1\bin\cmake\win\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install\local\fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	echo >nul && "C:\Program Files\JetBrains\CLion 2020.1\bin\cmake\win\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install\fast: preinstall\fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	echo >nul && "C:\Program Files\JetBrains\CLion 2020.1\bin\cmake\win\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install\fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	echo >nul && "C:\Program Files\JetBrains\CLion 2020.1\bin\cmake\win\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache

.PHONY : edit_cache\fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	echo >nul && "C:\Program Files\JetBrains\CLion 2020.1\bin\cmake\win\bin\cmake.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache

.PHONY : rebuild_cache\fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components\fast: list_install_components

.PHONY : list_install_components\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\GIT\UnconstrainedEngine\CMakeFiles D:\GIT\UnconstrainedEngine\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\GIT\UnconstrainedEngine\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean

.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PhysicsEngine

# Build rule for target.
PhysicsEngine: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) PhysicsEngine
.PHONY : PhysicsEngine

# fast build rule for target.
PhysicsEngine\fast:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\build
.PHONY : PhysicsEngine\fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall\fast:
	$(MAKE) -f Dependencies\Vendor\glfw\CMakeFiles\uninstall.dir\build.make /nologo -$(MAKEFLAGS) Dependencies\Vendor\glfw\CMakeFiles\uninstall.dir\build
.PHONY : uninstall\fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) glfw
.PHONY : glfw

# fast build rule for target.
glfw\fast:
	$(MAKE) -f Dependencies\Vendor\glfw\src\CMakeFiles\glfw.dir\build.make /nologo -$(MAKEFLAGS) Dependencies\Vendor\glfw\src\CMakeFiles\glfw.dir\build
.PHONY : glfw\fast

#=============================================================================
# Target rules for targets named glad-generate-files

# Build rule for target.
glad-generate-files: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) glad-generate-files
.PHONY : glad-generate-files

# fast build rule for target.
glad-generate-files\fast:
	$(MAKE) -f Dependencies\Vendor\glad\CMakeFiles\glad-generate-files.dir\build.make /nologo -$(MAKEFLAGS) Dependencies\Vendor\glad\CMakeFiles\glad-generate-files.dir\build
.PHONY : glad-generate-files\fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) glad
.PHONY : glad

# fast build rule for target.
glad\fast:
	$(MAKE) -f Dependencies\Vendor\glad\CMakeFiles\glad.dir\build.make /nologo -$(MAKEFLAGS) Dependencies\Vendor\glad\CMakeFiles\glad.dir\build
.PHONY : glad\fast

Dependencies\Source\Camera.obj: Dependencies\Source\Camera.cpp.obj

.PHONY : Dependencies\Source\Camera.obj

# target to build an object file
Dependencies\Source\Camera.cpp.obj:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\Camera.cpp.obj
.PHONY : Dependencies\Source\Camera.cpp.obj

Dependencies\Source\Camera.i: Dependencies\Source\Camera.cpp.i

.PHONY : Dependencies\Source\Camera.i

# target to preprocess a source file
Dependencies\Source\Camera.cpp.i:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\Camera.cpp.i
.PHONY : Dependencies\Source\Camera.cpp.i

Dependencies\Source\Camera.s: Dependencies\Source\Camera.cpp.s

.PHONY : Dependencies\Source\Camera.s

# target to generate assembly for a file
Dependencies\Source\Camera.cpp.s:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\Camera.cpp.s
.PHONY : Dependencies\Source\Camera.cpp.s

Dependencies\Source\Colliders.obj: Dependencies\Source\Colliders.cpp.obj

.PHONY : Dependencies\Source\Colliders.obj

# target to build an object file
Dependencies\Source\Colliders.cpp.obj:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\Colliders.cpp.obj
.PHONY : Dependencies\Source\Colliders.cpp.obj

Dependencies\Source\Colliders.i: Dependencies\Source\Colliders.cpp.i

.PHONY : Dependencies\Source\Colliders.i

# target to preprocess a source file
Dependencies\Source\Colliders.cpp.i:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\Colliders.cpp.i
.PHONY : Dependencies\Source\Colliders.cpp.i

Dependencies\Source\Colliders.s: Dependencies\Source\Colliders.cpp.s

.PHONY : Dependencies\Source\Colliders.s

# target to generate assembly for a file
Dependencies\Source\Colliders.cpp.s:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\Colliders.cpp.s
.PHONY : Dependencies\Source\Colliders.cpp.s

Dependencies\Source\CollisionAlgos.obj: Dependencies\Source\CollisionAlgos.cpp.obj

.PHONY : Dependencies\Source\CollisionAlgos.obj

# target to build an object file
Dependencies\Source\CollisionAlgos.cpp.obj:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\CollisionAlgos.cpp.obj
.PHONY : Dependencies\Source\CollisionAlgos.cpp.obj

Dependencies\Source\CollisionAlgos.i: Dependencies\Source\CollisionAlgos.cpp.i

.PHONY : Dependencies\Source\CollisionAlgos.i

# target to preprocess a source file
Dependencies\Source\CollisionAlgos.cpp.i:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\CollisionAlgos.cpp.i
.PHONY : Dependencies\Source\CollisionAlgos.cpp.i

Dependencies\Source\CollisionAlgos.s: Dependencies\Source\CollisionAlgos.cpp.s

.PHONY : Dependencies\Source\CollisionAlgos.s

# target to generate assembly for a file
Dependencies\Source\CollisionAlgos.cpp.s:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\CollisionAlgos.cpp.s
.PHONY : Dependencies\Source\CollisionAlgos.cpp.s

Dependencies\Source\Constraint.obj: Dependencies\Source\Constraint.cpp.obj

.PHONY : Dependencies\Source\Constraint.obj

# target to build an object file
Dependencies\Source\Constraint.cpp.obj:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\Constraint.cpp.obj
.PHONY : Dependencies\Source\Constraint.cpp.obj

Dependencies\Source\Constraint.i: Dependencies\Source\Constraint.cpp.i

.PHONY : Dependencies\Source\Constraint.i

# target to preprocess a source file
Dependencies\Source\Constraint.cpp.i:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\Constraint.cpp.i
.PHONY : Dependencies\Source\Constraint.cpp.i

Dependencies\Source\Constraint.s: Dependencies\Source\Constraint.cpp.s

.PHONY : Dependencies\Source\Constraint.s

# target to generate assembly for a file
Dependencies\Source\Constraint.cpp.s:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\Constraint.cpp.s
.PHONY : Dependencies\Source\Constraint.cpp.s

Dependencies\Source\Debug.obj: Dependencies\Source\Debug.cpp.obj

.PHONY : Dependencies\Source\Debug.obj

# target to build an object file
Dependencies\Source\Debug.cpp.obj:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\Debug.cpp.obj
.PHONY : Dependencies\Source\Debug.cpp.obj

Dependencies\Source\Debug.i: Dependencies\Source\Debug.cpp.i

.PHONY : Dependencies\Source\Debug.i

# target to preprocess a source file
Dependencies\Source\Debug.cpp.i:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\Debug.cpp.i
.PHONY : Dependencies\Source\Debug.cpp.i

Dependencies\Source\Debug.s: Dependencies\Source\Debug.cpp.s

.PHONY : Dependencies\Source\Debug.s

# target to generate assembly for a file
Dependencies\Source\Debug.cpp.s:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\Debug.cpp.s
.PHONY : Dependencies\Source\Debug.cpp.s

Dependencies\Source\Main.obj: Dependencies\Source\Main.cpp.obj

.PHONY : Dependencies\Source\Main.obj

# target to build an object file
Dependencies\Source\Main.cpp.obj:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\Main.cpp.obj
.PHONY : Dependencies\Source\Main.cpp.obj

Dependencies\Source\Main.i: Dependencies\Source\Main.cpp.i

.PHONY : Dependencies\Source\Main.i

# target to preprocess a source file
Dependencies\Source\Main.cpp.i:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\Main.cpp.i
.PHONY : Dependencies\Source\Main.cpp.i

Dependencies\Source\Main.s: Dependencies\Source\Main.cpp.s

.PHONY : Dependencies\Source\Main.s

# target to generate assembly for a file
Dependencies\Source\Main.cpp.s:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\Main.cpp.s
.PHONY : Dependencies\Source\Main.cpp.s

Dependencies\Source\Mesh.obj: Dependencies\Source\Mesh.cpp.obj

.PHONY : Dependencies\Source\Mesh.obj

# target to build an object file
Dependencies\Source\Mesh.cpp.obj:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\Mesh.cpp.obj
.PHONY : Dependencies\Source\Mesh.cpp.obj

Dependencies\Source\Mesh.i: Dependencies\Source\Mesh.cpp.i

.PHONY : Dependencies\Source\Mesh.i

# target to preprocess a source file
Dependencies\Source\Mesh.cpp.i:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\Mesh.cpp.i
.PHONY : Dependencies\Source\Mesh.cpp.i

Dependencies\Source\Mesh.s: Dependencies\Source\Mesh.cpp.s

.PHONY : Dependencies\Source\Mesh.s

# target to generate assembly for a file
Dependencies\Source\Mesh.cpp.s:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\Mesh.cpp.s
.PHONY : Dependencies\Source\Mesh.cpp.s

Dependencies\Source\ObjLoad.obj: Dependencies\Source\ObjLoad.cpp.obj

.PHONY : Dependencies\Source\ObjLoad.obj

# target to build an object file
Dependencies\Source\ObjLoad.cpp.obj:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\ObjLoad.cpp.obj
.PHONY : Dependencies\Source\ObjLoad.cpp.obj

Dependencies\Source\ObjLoad.i: Dependencies\Source\ObjLoad.cpp.i

.PHONY : Dependencies\Source\ObjLoad.i

# target to preprocess a source file
Dependencies\Source\ObjLoad.cpp.i:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\ObjLoad.cpp.i
.PHONY : Dependencies\Source\ObjLoad.cpp.i

Dependencies\Source\ObjLoad.s: Dependencies\Source\ObjLoad.cpp.s

.PHONY : Dependencies\Source\ObjLoad.s

# target to generate assembly for a file
Dependencies\Source\ObjLoad.cpp.s:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\ObjLoad.cpp.s
.PHONY : Dependencies\Source\ObjLoad.cpp.s

Dependencies\Source\Octree.obj: Dependencies\Source\Octree.cpp.obj

.PHONY : Dependencies\Source\Octree.obj

# target to build an object file
Dependencies\Source\Octree.cpp.obj:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\Octree.cpp.obj
.PHONY : Dependencies\Source\Octree.cpp.obj

Dependencies\Source\Octree.i: Dependencies\Source\Octree.cpp.i

.PHONY : Dependencies\Source\Octree.i

# target to preprocess a source file
Dependencies\Source\Octree.cpp.i:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\Octree.cpp.i
.PHONY : Dependencies\Source\Octree.cpp.i

Dependencies\Source\Octree.s: Dependencies\Source\Octree.cpp.s

.PHONY : Dependencies\Source\Octree.s

# target to generate assembly for a file
Dependencies\Source\Octree.cpp.s:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\Octree.cpp.s
.PHONY : Dependencies\Source\Octree.cpp.s

Dependencies\Source\PhysicsWorld.obj: Dependencies\Source\PhysicsWorld.cpp.obj

.PHONY : Dependencies\Source\PhysicsWorld.obj

# target to build an object file
Dependencies\Source\PhysicsWorld.cpp.obj:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\PhysicsWorld.cpp.obj
.PHONY : Dependencies\Source\PhysicsWorld.cpp.obj

Dependencies\Source\PhysicsWorld.i: Dependencies\Source\PhysicsWorld.cpp.i

.PHONY : Dependencies\Source\PhysicsWorld.i

# target to preprocess a source file
Dependencies\Source\PhysicsWorld.cpp.i:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\PhysicsWorld.cpp.i
.PHONY : Dependencies\Source\PhysicsWorld.cpp.i

Dependencies\Source\PhysicsWorld.s: Dependencies\Source\PhysicsWorld.cpp.s

.PHONY : Dependencies\Source\PhysicsWorld.s

# target to generate assembly for a file
Dependencies\Source\PhysicsWorld.cpp.s:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\PhysicsWorld.cpp.s
.PHONY : Dependencies\Source\PhysicsWorld.cpp.s

Dependencies\Source\RigidBody.obj: Dependencies\Source\RigidBody.cpp.obj

.PHONY : Dependencies\Source\RigidBody.obj

# target to build an object file
Dependencies\Source\RigidBody.cpp.obj:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\RigidBody.cpp.obj
.PHONY : Dependencies\Source\RigidBody.cpp.obj

Dependencies\Source\RigidBody.i: Dependencies\Source\RigidBody.cpp.i

.PHONY : Dependencies\Source\RigidBody.i

# target to preprocess a source file
Dependencies\Source\RigidBody.cpp.i:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\RigidBody.cpp.i
.PHONY : Dependencies\Source\RigidBody.cpp.i

Dependencies\Source\RigidBody.s: Dependencies\Source\RigidBody.cpp.s

.PHONY : Dependencies\Source\RigidBody.s

# target to generate assembly for a file
Dependencies\Source\RigidBody.cpp.s:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\RigidBody.cpp.s
.PHONY : Dependencies\Source\RigidBody.cpp.s

Dependencies\Source\Shader.obj: Dependencies\Source\Shader.cpp.obj

.PHONY : Dependencies\Source\Shader.obj

# target to build an object file
Dependencies\Source\Shader.cpp.obj:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\Shader.cpp.obj
.PHONY : Dependencies\Source\Shader.cpp.obj

Dependencies\Source\Shader.i: Dependencies\Source\Shader.cpp.i

.PHONY : Dependencies\Source\Shader.i

# target to preprocess a source file
Dependencies\Source\Shader.cpp.i:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\Shader.cpp.i
.PHONY : Dependencies\Source\Shader.cpp.i

Dependencies\Source\Shader.s: Dependencies\Source\Shader.cpp.s

.PHONY : Dependencies\Source\Shader.s

# target to generate assembly for a file
Dependencies\Source\Shader.cpp.s:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Source\Shader.cpp.s
.PHONY : Dependencies\Source\Shader.cpp.s

Dependencies\Vendor\ImGuizmo\ImCurveEdit.obj: Dependencies\Vendor\ImGuizmo\ImCurveEdit.cpp.obj

.PHONY : Dependencies\Vendor\ImGuizmo\ImCurveEdit.obj

# target to build an object file
Dependencies\Vendor\ImGuizmo\ImCurveEdit.cpp.obj:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\ImGuizmo\ImCurveEdit.cpp.obj
.PHONY : Dependencies\Vendor\ImGuizmo\ImCurveEdit.cpp.obj

Dependencies\Vendor\ImGuizmo\ImCurveEdit.i: Dependencies\Vendor\ImGuizmo\ImCurveEdit.cpp.i

.PHONY : Dependencies\Vendor\ImGuizmo\ImCurveEdit.i

# target to preprocess a source file
Dependencies\Vendor\ImGuizmo\ImCurveEdit.cpp.i:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\ImGuizmo\ImCurveEdit.cpp.i
.PHONY : Dependencies\Vendor\ImGuizmo\ImCurveEdit.cpp.i

Dependencies\Vendor\ImGuizmo\ImCurveEdit.s: Dependencies\Vendor\ImGuizmo\ImCurveEdit.cpp.s

.PHONY : Dependencies\Vendor\ImGuizmo\ImCurveEdit.s

# target to generate assembly for a file
Dependencies\Vendor\ImGuizmo\ImCurveEdit.cpp.s:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\ImGuizmo\ImCurveEdit.cpp.s
.PHONY : Dependencies\Vendor\ImGuizmo\ImCurveEdit.cpp.s

Dependencies\Vendor\ImGuizmo\ImGradient.obj: Dependencies\Vendor\ImGuizmo\ImGradient.cpp.obj

.PHONY : Dependencies\Vendor\ImGuizmo\ImGradient.obj

# target to build an object file
Dependencies\Vendor\ImGuizmo\ImGradient.cpp.obj:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\ImGuizmo\ImGradient.cpp.obj
.PHONY : Dependencies\Vendor\ImGuizmo\ImGradient.cpp.obj

Dependencies\Vendor\ImGuizmo\ImGradient.i: Dependencies\Vendor\ImGuizmo\ImGradient.cpp.i

.PHONY : Dependencies\Vendor\ImGuizmo\ImGradient.i

# target to preprocess a source file
Dependencies\Vendor\ImGuizmo\ImGradient.cpp.i:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\ImGuizmo\ImGradient.cpp.i
.PHONY : Dependencies\Vendor\ImGuizmo\ImGradient.cpp.i

Dependencies\Vendor\ImGuizmo\ImGradient.s: Dependencies\Vendor\ImGuizmo\ImGradient.cpp.s

.PHONY : Dependencies\Vendor\ImGuizmo\ImGradient.s

# target to generate assembly for a file
Dependencies\Vendor\ImGuizmo\ImGradient.cpp.s:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\ImGuizmo\ImGradient.cpp.s
.PHONY : Dependencies\Vendor\ImGuizmo\ImGradient.cpp.s

Dependencies\Vendor\ImGuizmo\ImGuizmo.obj: Dependencies\Vendor\ImGuizmo\ImGuizmo.cpp.obj

.PHONY : Dependencies\Vendor\ImGuizmo\ImGuizmo.obj

# target to build an object file
Dependencies\Vendor\ImGuizmo\ImGuizmo.cpp.obj:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\ImGuizmo\ImGuizmo.cpp.obj
.PHONY : Dependencies\Vendor\ImGuizmo\ImGuizmo.cpp.obj

Dependencies\Vendor\ImGuizmo\ImGuizmo.i: Dependencies\Vendor\ImGuizmo\ImGuizmo.cpp.i

.PHONY : Dependencies\Vendor\ImGuizmo\ImGuizmo.i

# target to preprocess a source file
Dependencies\Vendor\ImGuizmo\ImGuizmo.cpp.i:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\ImGuizmo\ImGuizmo.cpp.i
.PHONY : Dependencies\Vendor\ImGuizmo\ImGuizmo.cpp.i

Dependencies\Vendor\ImGuizmo\ImGuizmo.s: Dependencies\Vendor\ImGuizmo\ImGuizmo.cpp.s

.PHONY : Dependencies\Vendor\ImGuizmo\ImGuizmo.s

# target to generate assembly for a file
Dependencies\Vendor\ImGuizmo\ImGuizmo.cpp.s:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\ImGuizmo\ImGuizmo.cpp.s
.PHONY : Dependencies\Vendor\ImGuizmo\ImGuizmo.cpp.s

Dependencies\Vendor\ImGuizmo\ImSequencer.obj: Dependencies\Vendor\ImGuizmo\ImSequencer.cpp.obj

.PHONY : Dependencies\Vendor\ImGuizmo\ImSequencer.obj

# target to build an object file
Dependencies\Vendor\ImGuizmo\ImSequencer.cpp.obj:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\ImGuizmo\ImSequencer.cpp.obj
.PHONY : Dependencies\Vendor\ImGuizmo\ImSequencer.cpp.obj

Dependencies\Vendor\ImGuizmo\ImSequencer.i: Dependencies\Vendor\ImGuizmo\ImSequencer.cpp.i

.PHONY : Dependencies\Vendor\ImGuizmo\ImSequencer.i

# target to preprocess a source file
Dependencies\Vendor\ImGuizmo\ImSequencer.cpp.i:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\ImGuizmo\ImSequencer.cpp.i
.PHONY : Dependencies\Vendor\ImGuizmo\ImSequencer.cpp.i

Dependencies\Vendor\ImGuizmo\ImSequencer.s: Dependencies\Vendor\ImGuizmo\ImSequencer.cpp.s

.PHONY : Dependencies\Vendor\ImGuizmo\ImSequencer.s

# target to generate assembly for a file
Dependencies\Vendor\ImGuizmo\ImSequencer.cpp.s:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\ImGuizmo\ImSequencer.cpp.s
.PHONY : Dependencies\Vendor\ImGuizmo\ImSequencer.cpp.s

Dependencies\Vendor\glad\src\glad.obj: Dependencies\Vendor\glad\src\glad.c.obj

.PHONY : Dependencies\Vendor\glad\src\glad.obj

# target to build an object file
Dependencies\Vendor\glad\src\glad.c.obj:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\glad\src\glad.c.obj
.PHONY : Dependencies\Vendor\glad\src\glad.c.obj

Dependencies\Vendor\glad\src\glad.i: Dependencies\Vendor\glad\src\glad.c.i

.PHONY : Dependencies\Vendor\glad\src\glad.i

# target to preprocess a source file
Dependencies\Vendor\glad\src\glad.c.i:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\glad\src\glad.c.i
.PHONY : Dependencies\Vendor\glad\src\glad.c.i

Dependencies\Vendor\glad\src\glad.s: Dependencies\Vendor\glad\src\glad.c.s

.PHONY : Dependencies\Vendor\glad\src\glad.s

# target to generate assembly for a file
Dependencies\Vendor\glad\src\glad.c.s:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\glad\src\glad.c.s
.PHONY : Dependencies\Vendor\glad\src\glad.c.s

Dependencies\Vendor\imgui\backends\imgui_impl_glfw.obj: Dependencies\Vendor\imgui\backends\imgui_impl_glfw.cpp.obj

.PHONY : Dependencies\Vendor\imgui\backends\imgui_impl_glfw.obj

# target to build an object file
Dependencies\Vendor\imgui\backends\imgui_impl_glfw.cpp.obj:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\imgui\backends\imgui_impl_glfw.cpp.obj
.PHONY : Dependencies\Vendor\imgui\backends\imgui_impl_glfw.cpp.obj

Dependencies\Vendor\imgui\backends\imgui_impl_glfw.i: Dependencies\Vendor\imgui\backends\imgui_impl_glfw.cpp.i

.PHONY : Dependencies\Vendor\imgui\backends\imgui_impl_glfw.i

# target to preprocess a source file
Dependencies\Vendor\imgui\backends\imgui_impl_glfw.cpp.i:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\imgui\backends\imgui_impl_glfw.cpp.i
.PHONY : Dependencies\Vendor\imgui\backends\imgui_impl_glfw.cpp.i

Dependencies\Vendor\imgui\backends\imgui_impl_glfw.s: Dependencies\Vendor\imgui\backends\imgui_impl_glfw.cpp.s

.PHONY : Dependencies\Vendor\imgui\backends\imgui_impl_glfw.s

# target to generate assembly for a file
Dependencies\Vendor\imgui\backends\imgui_impl_glfw.cpp.s:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\imgui\backends\imgui_impl_glfw.cpp.s
.PHONY : Dependencies\Vendor\imgui\backends\imgui_impl_glfw.cpp.s

Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.obj: Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.cpp.obj

.PHONY : Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.obj

# target to build an object file
Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.cpp.obj:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.cpp.obj
.PHONY : Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.cpp.obj

Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.i: Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.cpp.i

.PHONY : Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.i

# target to preprocess a source file
Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.cpp.i:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.cpp.i
.PHONY : Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.cpp.i

Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.s: Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.cpp.s

.PHONY : Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.s

# target to generate assembly for a file
Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.cpp.s:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.cpp.s
.PHONY : Dependencies\Vendor\imgui\backends\imgui_impl_opengl3.cpp.s

Dependencies\Vendor\imgui\imgui.obj: Dependencies\Vendor\imgui\imgui.cpp.obj

.PHONY : Dependencies\Vendor\imgui\imgui.obj

# target to build an object file
Dependencies\Vendor\imgui\imgui.cpp.obj:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\imgui\imgui.cpp.obj
.PHONY : Dependencies\Vendor\imgui\imgui.cpp.obj

Dependencies\Vendor\imgui\imgui.i: Dependencies\Vendor\imgui\imgui.cpp.i

.PHONY : Dependencies\Vendor\imgui\imgui.i

# target to preprocess a source file
Dependencies\Vendor\imgui\imgui.cpp.i:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\imgui\imgui.cpp.i
.PHONY : Dependencies\Vendor\imgui\imgui.cpp.i

Dependencies\Vendor\imgui\imgui.s: Dependencies\Vendor\imgui\imgui.cpp.s

.PHONY : Dependencies\Vendor\imgui\imgui.s

# target to generate assembly for a file
Dependencies\Vendor\imgui\imgui.cpp.s:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\imgui\imgui.cpp.s
.PHONY : Dependencies\Vendor\imgui\imgui.cpp.s

Dependencies\Vendor\imgui\imgui_demo.obj: Dependencies\Vendor\imgui\imgui_demo.cpp.obj

.PHONY : Dependencies\Vendor\imgui\imgui_demo.obj

# target to build an object file
Dependencies\Vendor\imgui\imgui_demo.cpp.obj:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\imgui\imgui_demo.cpp.obj
.PHONY : Dependencies\Vendor\imgui\imgui_demo.cpp.obj

Dependencies\Vendor\imgui\imgui_demo.i: Dependencies\Vendor\imgui\imgui_demo.cpp.i

.PHONY : Dependencies\Vendor\imgui\imgui_demo.i

# target to preprocess a source file
Dependencies\Vendor\imgui\imgui_demo.cpp.i:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\imgui\imgui_demo.cpp.i
.PHONY : Dependencies\Vendor\imgui\imgui_demo.cpp.i

Dependencies\Vendor\imgui\imgui_demo.s: Dependencies\Vendor\imgui\imgui_demo.cpp.s

.PHONY : Dependencies\Vendor\imgui\imgui_demo.s

# target to generate assembly for a file
Dependencies\Vendor\imgui\imgui_demo.cpp.s:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\imgui\imgui_demo.cpp.s
.PHONY : Dependencies\Vendor\imgui\imgui_demo.cpp.s

Dependencies\Vendor\imgui\imgui_draw.obj: Dependencies\Vendor\imgui\imgui_draw.cpp.obj

.PHONY : Dependencies\Vendor\imgui\imgui_draw.obj

# target to build an object file
Dependencies\Vendor\imgui\imgui_draw.cpp.obj:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\imgui\imgui_draw.cpp.obj
.PHONY : Dependencies\Vendor\imgui\imgui_draw.cpp.obj

Dependencies\Vendor\imgui\imgui_draw.i: Dependencies\Vendor\imgui\imgui_draw.cpp.i

.PHONY : Dependencies\Vendor\imgui\imgui_draw.i

# target to preprocess a source file
Dependencies\Vendor\imgui\imgui_draw.cpp.i:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\imgui\imgui_draw.cpp.i
.PHONY : Dependencies\Vendor\imgui\imgui_draw.cpp.i

Dependencies\Vendor\imgui\imgui_draw.s: Dependencies\Vendor\imgui\imgui_draw.cpp.s

.PHONY : Dependencies\Vendor\imgui\imgui_draw.s

# target to generate assembly for a file
Dependencies\Vendor\imgui\imgui_draw.cpp.s:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\imgui\imgui_draw.cpp.s
.PHONY : Dependencies\Vendor\imgui\imgui_draw.cpp.s

Dependencies\Vendor\imgui\imgui_tables.obj: Dependencies\Vendor\imgui\imgui_tables.cpp.obj

.PHONY : Dependencies\Vendor\imgui\imgui_tables.obj

# target to build an object file
Dependencies\Vendor\imgui\imgui_tables.cpp.obj:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\imgui\imgui_tables.cpp.obj
.PHONY : Dependencies\Vendor\imgui\imgui_tables.cpp.obj

Dependencies\Vendor\imgui\imgui_tables.i: Dependencies\Vendor\imgui\imgui_tables.cpp.i

.PHONY : Dependencies\Vendor\imgui\imgui_tables.i

# target to preprocess a source file
Dependencies\Vendor\imgui\imgui_tables.cpp.i:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\imgui\imgui_tables.cpp.i
.PHONY : Dependencies\Vendor\imgui\imgui_tables.cpp.i

Dependencies\Vendor\imgui\imgui_tables.s: Dependencies\Vendor\imgui\imgui_tables.cpp.s

.PHONY : Dependencies\Vendor\imgui\imgui_tables.s

# target to generate assembly for a file
Dependencies\Vendor\imgui\imgui_tables.cpp.s:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\imgui\imgui_tables.cpp.s
.PHONY : Dependencies\Vendor\imgui\imgui_tables.cpp.s

Dependencies\Vendor\imgui\imgui_widgets.obj: Dependencies\Vendor\imgui\imgui_widgets.cpp.obj

.PHONY : Dependencies\Vendor\imgui\imgui_widgets.obj

# target to build an object file
Dependencies\Vendor\imgui\imgui_widgets.cpp.obj:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\imgui\imgui_widgets.cpp.obj
.PHONY : Dependencies\Vendor\imgui\imgui_widgets.cpp.obj

Dependencies\Vendor\imgui\imgui_widgets.i: Dependencies\Vendor\imgui\imgui_widgets.cpp.i

.PHONY : Dependencies\Vendor\imgui\imgui_widgets.i

# target to preprocess a source file
Dependencies\Vendor\imgui\imgui_widgets.cpp.i:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\imgui\imgui_widgets.cpp.i
.PHONY : Dependencies\Vendor\imgui\imgui_widgets.cpp.i

Dependencies\Vendor\imgui\imgui_widgets.s: Dependencies\Vendor\imgui\imgui_widgets.cpp.s

.PHONY : Dependencies\Vendor\imgui\imgui_widgets.s

# target to generate assembly for a file
Dependencies\Vendor\imgui\imgui_widgets.cpp.s:
	$(MAKE) -f CMakeFiles\PhysicsEngine.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\PhysicsEngine.dir\Dependencies\Vendor\imgui\imgui_widgets.cpp.s
.PHONY : Dependencies\Vendor\imgui\imgui_widgets.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... install/local
	@echo ... install
	@echo ... edit_cache
	@echo ... PhysicsEngine
	@echo ... rebuild_cache
	@echo ... list_install_components
	@echo ... uninstall
	@echo ... glfw
	@echo ... glad-generate-files
	@echo ... glad
	@echo ... Dependencies/Source/Camera.obj
	@echo ... Dependencies/Source/Camera.i
	@echo ... Dependencies/Source/Camera.s
	@echo ... Dependencies/Source/Colliders.obj
	@echo ... Dependencies/Source/Colliders.i
	@echo ... Dependencies/Source/Colliders.s
	@echo ... Dependencies/Source/CollisionAlgos.obj
	@echo ... Dependencies/Source/CollisionAlgos.i
	@echo ... Dependencies/Source/CollisionAlgos.s
	@echo ... Dependencies/Source/Constraint.obj
	@echo ... Dependencies/Source/Constraint.i
	@echo ... Dependencies/Source/Constraint.s
	@echo ... Dependencies/Source/Debug.obj
	@echo ... Dependencies/Source/Debug.i
	@echo ... Dependencies/Source/Debug.s
	@echo ... Dependencies/Source/Main.obj
	@echo ... Dependencies/Source/Main.i
	@echo ... Dependencies/Source/Main.s
	@echo ... Dependencies/Source/Mesh.obj
	@echo ... Dependencies/Source/Mesh.i
	@echo ... Dependencies/Source/Mesh.s
	@echo ... Dependencies/Source/ObjLoad.obj
	@echo ... Dependencies/Source/ObjLoad.i
	@echo ... Dependencies/Source/ObjLoad.s
	@echo ... Dependencies/Source/Octree.obj
	@echo ... Dependencies/Source/Octree.i
	@echo ... Dependencies/Source/Octree.s
	@echo ... Dependencies/Source/PhysicsWorld.obj
	@echo ... Dependencies/Source/PhysicsWorld.i
	@echo ... Dependencies/Source/PhysicsWorld.s
	@echo ... Dependencies/Source/RigidBody.obj
	@echo ... Dependencies/Source/RigidBody.i
	@echo ... Dependencies/Source/RigidBody.s
	@echo ... Dependencies/Source/Shader.obj
	@echo ... Dependencies/Source/Shader.i
	@echo ... Dependencies/Source/Shader.s
	@echo ... Dependencies/Vendor/ImGuizmo/ImCurveEdit.obj
	@echo ... Dependencies/Vendor/ImGuizmo/ImCurveEdit.i
	@echo ... Dependencies/Vendor/ImGuizmo/ImCurveEdit.s
	@echo ... Dependencies/Vendor/ImGuizmo/ImGradient.obj
	@echo ... Dependencies/Vendor/ImGuizmo/ImGradient.i
	@echo ... Dependencies/Vendor/ImGuizmo/ImGradient.s
	@echo ... Dependencies/Vendor/ImGuizmo/ImGuizmo.obj
	@echo ... Dependencies/Vendor/ImGuizmo/ImGuizmo.i
	@echo ... Dependencies/Vendor/ImGuizmo/ImGuizmo.s
	@echo ... Dependencies/Vendor/ImGuizmo/ImSequencer.obj
	@echo ... Dependencies/Vendor/ImGuizmo/ImSequencer.i
	@echo ... Dependencies/Vendor/ImGuizmo/ImSequencer.s
	@echo ... Dependencies/Vendor/glad/src/glad.obj
	@echo ... Dependencies/Vendor/glad/src/glad.i
	@echo ... Dependencies/Vendor/glad/src/glad.s
	@echo ... Dependencies/Vendor/imgui/backends/imgui_impl_glfw.obj
	@echo ... Dependencies/Vendor/imgui/backends/imgui_impl_glfw.i
	@echo ... Dependencies/Vendor/imgui/backends/imgui_impl_glfw.s
	@echo ... Dependencies/Vendor/imgui/backends/imgui_impl_opengl3.obj
	@echo ... Dependencies/Vendor/imgui/backends/imgui_impl_opengl3.i
	@echo ... Dependencies/Vendor/imgui/backends/imgui_impl_opengl3.s
	@echo ... Dependencies/Vendor/imgui/imgui.obj
	@echo ... Dependencies/Vendor/imgui/imgui.i
	@echo ... Dependencies/Vendor/imgui/imgui.s
	@echo ... Dependencies/Vendor/imgui/imgui_demo.obj
	@echo ... Dependencies/Vendor/imgui/imgui_demo.i
	@echo ... Dependencies/Vendor/imgui/imgui_demo.s
	@echo ... Dependencies/Vendor/imgui/imgui_draw.obj
	@echo ... Dependencies/Vendor/imgui/imgui_draw.i
	@echo ... Dependencies/Vendor/imgui/imgui_draw.s
	@echo ... Dependencies/Vendor/imgui/imgui_tables.obj
	@echo ... Dependencies/Vendor/imgui/imgui_tables.i
	@echo ... Dependencies/Vendor/imgui/imgui_tables.s
	@echo ... Dependencies/Vendor/imgui/imgui_widgets.obj
	@echo ... Dependencies/Vendor/imgui/imgui_widgets.i
	@echo ... Dependencies/Vendor/imgui/imgui_widgets.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

